INSERT INTO labels values(NULL, NULL, NULL, NULL, 'diet', 'balanced');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'diet', 'high-fiber');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'diet', 'high-protein');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'diet', 'low-carb');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'diet', 'low-fat');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'diet', 'low-sodium');

INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'alcohol-cocktail');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'alcohol-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'celery-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'crustacean-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'dairy-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'DASH');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'egg-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'fish-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'fodmap-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'gluten-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'immuno-supportive');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'keto-friendly');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'kidney-friendly');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'kosher');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'low-potassium');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'low-sugar');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'lupine-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'Mediterranean');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'mollusk-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'mustard-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'No-oil-added');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'paleo');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'peanut-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'pescatarian');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'pork-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'red-meat-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'sesame-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'shellfish-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'soy-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'sugar-conscious');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'sulfite-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'tree-nut-free');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'vegan');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'vegetarian');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'health', 'wheat-free');

INSERT INTO labels values(NULL, NULL, NULL, NULL, 'mealType', 'breakfast');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'mealType', 'brunch');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'mealType', 'lunch');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'mealType', 'dinner');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'mealType', 'snack');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'mealType', 'teatime');

INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'alcohol cocktail');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'biscuits and cookies');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'bread');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'cereals');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'condiments and sauces');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'desserts');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'drinks');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'egg');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'ice cream and custard');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'main course');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'pancake');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'pasta');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'pastry');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'pies and tarts');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'pizza');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'preps');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'preserve');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'salad');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'sandwiches');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'seafood');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'side dish');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'soup');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'special occasions');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'starter');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'dishType', 'sweets');

INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'american');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'asian');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'british');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'caribbean');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'central europe');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'chinese');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'eastern europe');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'french');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'greek');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'indian');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'italian');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'japanese');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'korean');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'kosher');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'mediterranean');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'mexican');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'middle eastern');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'nordic');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'south american');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'south east asian');
INSERT INTO labels values(NULL, NULL, NULL, NULL, 'cuisineType', 'world');
